---
title: "Seldin Report: Secreted excluding Extracellular Matrix"
author: "Angela Yoder"
date: "`r Sys.Date()`"
---

**The goals of this program are:**

1. See if significance improves after removing secreted proteins that are annotated for extracellular matrix

```{r echo=FALSE, message=FALSE}

library(tidyverse)
library(reshape2)
library(WGCNA)
#library(reshape)
#library(ggplot2)

# Data Input

#setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data/")
setwd("C:/Users/yodeange/OneDrive - The University of Colorado Denver/Saba Lab/Data")
protein_liver = read.csv("Liver_WGCNA.csv")
protein_brain = read.csv("Brain_WGCNA.csv")
secreted_protein_brain = read.csv("Secreted_Brain.csv")
secreted_protein_liver = read.csv("Secreted_Liver.csv")
notsecreted_protein_brain = read.csv("NotSecreted_Brain.csv")
notsecreted_protein_liver = read.csv("NotSecreted_Liver.csv")
sec_annot = read.csv("Sec_Annotation.csv")
#tissuespec_protein_brain = read.csv("TissueSpecific_Protein_Brain.csv")
#tissuespec_protein_liver = read.csv("TissueSpecific_Protein_Liver.csv")
ts_protein_brain = read.csv("TissueSpecific2_Protein_Brain.csv")
ts_protein_liver = read.csv("TissueSpecific2_Protein_Liver.csv")
tsns_protein_brain = read.csv("NSTissueSpecific_Protein_Brain.csv")
tsns_protein_liver = read.csv("NSTissueSpecific_Protein_Liver.csv")

#new_sec = read.delim("uniprot-rat+secreted+locations_(location__Secreted+[SL-0243]_+type--.tab.gz")
extracell = read.delim("uniprot-rat+extracellular+matrix+organism__Rattus+norvegicus+(Rat)+[10--.tab")
brain_uniprot = read.csv("Brain_Uniprot.csv")
liver_uniprot = read.csv("Liver_Uniprot.csv")

fix.read.csv = function(x)
{
  names = x[,1]
  gee = x[,2:dim(x)[2]]
  rownames(gee) = names
  return(gee)
}

protein_liver = fix.read.csv(protein_liver)
protein_brain = fix.read.csv(protein_brain)
secreted_protein_brain = fix.read.csv(secreted_protein_brain)
secreted_protein_liver = fix.read.csv(secreted_protein_liver)
notsecreted_protein_brain = fix.read.csv(notsecreted_protein_brain)
notsecreted_protein_liver = fix.read.csv(notsecreted_protein_liver)
sec_annot = fix.read.csv(sec_annot)
#tissuespec_protein_brain = fix.read.csv(tissuespec_protein_brain)
#tissuespec_protein_liver = fix.read.csv(tissuespec_protein_liver)
ts_protein_brain = fix.read.csv(ts_protein_brain)
ts_protein_liver = fix.read.csv(ts_protein_liver)
tsns_protein_brain = fix.read.csv(tsns_protein_brain)
tsns_protein_liver = fix.read.csv(tsns_protein_liver)
brain_uniprot = fix.read.csv(brain_uniprot)
liver_uniprot = fix.read.csv(liver_uniprot)

```


```{r, echo = FALSE}

# get ensembl ids for extracellular

`%!in%` <- Negate(`%in%`)

ens_brain = unique(brain_uniprot$ensembl_gene_id[brain_uniprot$uniprot_gn_id %in% extracell$Entry])
ens_liver = unique(liver_uniprot$ensembl_gene_id[liver_uniprot$uniprot_gn_id %in% extracell$Entry])

secreted_ens_brain = unique(colnames(secreted_protein_brain)[colnames(secreted_protein_brain) %in% ens_brain])
secreted_ens_liver = unique(colnames(secreted_protein_liver)[colnames(secreted_protein_liver) %in% ens_liver])

secnoextra_protein_brain = secreted_protein_brain[, colnames(secreted_protein_brain) %!in% secreted_ens_brain]
secnoextra_protein_liver = secreted_protein_liver[, colnames(secreted_protein_liver) %!in% secreted_ens_liver]


```

There is still no significant difference between secreted and non-secreted Ssec scores. 

```{r, echo = FALSE}

notsecreted.1_protein_brain = cbind(notsecreted_protein_brain, protein_brain[colnames(protein_brain) %in% secreted_ens_brain])
notsecreted.1_protein_liver = cbind(notsecreted_protein_liver, protein_brain[colnames(protein_liver) %in% secreted_ens_liver])

#### Secreted ####
## BRAIN ##
target_liver = cbind(ts_protein_liver, tsns_protein_liver)

brain.liv = bicorAndPvalue(secnoextra_protein_brain, target_liver, use = 'pairwise.complete.obs')
# brain.liv$p

scores = rowSums(-log(brain.liv$p))

sec_Ssec_brain = data.frame(Gene_symbol = names(scores), score = scores) %>%
  #filter(Gene_symbol %in% sec_annot$ensembl_gene_id) %>%
  mutate(Ssec = score / length(colnames(target_liver))) %>%
  dplyr::select(-score) %>%
  arrange(desc(Ssec))

#ts_Ssec_brain = Ssec_brain[Ssec_brain[,1] %in% colnames(ts_protein_brain),]
top_brain = head(sec_Ssec_brain[,1])
bot_brain = tail(sec_Ssec_brain[,1])


## LIVER ##

target_brain = cbind(ts_protein_brain, tsns_protein_brain)

liv.brain = bicorAndPvalue(secnoextra_protein_liver, target_brain, use = 'pairwise.complete.obs')
# brain.liv$p

scores = rowSums(-log(liv.brain$p))

sec_Ssec_liver = data.frame(Gene_symbol = names(scores), score = scores) %>%
  #filter(Gene_symbol %in% sec_annot$ensembl_gene_id) %>%
  mutate(Ssec = score / length(colnames(target_brain))) %>%
  dplyr::select(-score) %>%
  arrange(desc(Ssec))

#ts_Ssec_liver = Ssec_liver[Ssec_liver[,1] %in% colnames(ts_protein_liver),]
top_liver = head(sec_Ssec_liver[,1])
bot_liver = tail(sec_Ssec_liver[,1])

#### Not Secreted ####

## BRAIN ##

brain.liv.c = bicorAndPvalue(notsecreted.1_protein_brain, target_liver, use = 'pairwise.complete.obs')
# brain.liv$p

scores = rowSums(-log(brain.liv.c$p))

nsec_Ssec_brain = data.frame(Gene_symbol = names(scores), score = scores) %>%
  #filter(Gene_symbol %in% sec_annot$ensembl_gene_id) %>%
  mutate(Ssec = score / length(colnames(target_liver))) %>%
  dplyr::select(-score) %>%
  arrange(desc(Ssec))

#ts_Ssec_brain = Ssec_brain[Ssec_brain[,1] %in% colnames(ts_protein_brain),]
#top_brain = head(tsns_Ssec_brain[,1])
#bot_brain = tail(ts_Ssec_brain[,1])


## LIVER ##

liv.brain.c = bicorAndPvalue(notsecreted.1_protein_liver, target_brain, use = 'pairwise.complete.obs')
# brain.liv$p

scores = rowSums(-log(liv.brain.c$p))

nsec_Ssec_liver = data.frame(Gene_symbol = names(scores), score = scores) %>%
  #filter(Gene_symbol %in% sec_annot$ensembl_gene_id) %>%
  mutate(Ssec = score / length(colnames(target_brain))) %>%
  dplyr::select(-score) %>%
  arrange(desc(Ssec))

#ts_Ssec_liver = Ssec_liver[Ssec_liver[,1] %in% colnames(ts_protein_liver),]
#top_liver = head(ts_Ssec_liver[,1])
#bot_liver = tail(ts_Ssec_liver[,1])

####### Visualizations

#Brain
h1 = cbind(rep("Not Secreted brain", times = length(nsec_Ssec_brain$Ssec)), nsec_Ssec_brain$Ssec)
h2 = cbind(rep("Secreted brain", times = length(sec_Ssec_brain$Ssec)), sec_Ssec_brain$Ssec)

compare.b = rbind(h1, h2)
colnames(compare.b) = c("trt", "val")
compare.b = as.data.frame(compare.b)
compare.b$trt = as.factor(compare.b$trt)
compare.b$val = as.numeric(compare.b$val)


ggplot(compare.b, aes(val, color = trt)) + 
  geom_density() +
  labs(title="Brain Ssec Distribution: Tissue-Specific Non-Secreted v. Tissue-Specific Secreted", x = "Ssec", y = "Density")

# Liver
h1 = cbind(rep("Not Secreted liver", times = length(nsec_Ssec_liver$Ssec)), nsec_Ssec_liver$Ssec)
h2 = cbind(rep("Secreted liver", times = length(sec_Ssec_liver$Ssec)), sec_Ssec_liver$Ssec)

compare.l = rbind(h1, h2)
colnames(compare.l) = c("trt", "val")
compare.l = as.data.frame(compare.l)
compare.l$trt = as.factor(compare.l$trt)
compare.l$val = as.numeric(compare.l$val)


ggplot(compare.l, aes(val, color = trt)) + 
  geom_density() +
  labs(title="Liver Ssec Distribution: Tissue-Specific Non-Secreted v. Tissue-Specific Secreted", x = "Ssec", y = "Density")

#brain

wil.brain = coin::wilcox_test(val ~ trt, compare.b)
wil.brain

# liver

wil.liver = coin::wilcox_test(val ~ trt, compare.l)
wil.liver

# :'(


```