---
title: "Ssec Scores: Partial Correlation"
author: "Angela Yoder"
date: "`r Sys.Date()`"
---

**The goals of this program are:**

1. Compare theory behind partial midweight correlation and partial correlation
2. Calculate Partial Correlation, compare to biweight midcorrelation
3. Convert Partial Correlation to Ssec Scores
4. Look at distribution of Partial Correlation, QQ plots
5. Use permutation test from Seldin to check null distribution

Lambda???

```{r, echo = FALSE, message = FALSE}
library(WGCNA)
library(ppcor)
library(tidyverse)


setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data/")
#setwd("C:/Users/yodeange/OneDrive - The University of Colorado Denver/Saba Lab/Data")

tes.brain = read.csv("TissueSpecific2_Protein_Brain.csv")
tes.liver = read.csv("TissueSpecific2_Protein_Liver.csv")
tens.brain = read.csv("NSTissueSpecific_Protein_Brain.csv")
tens.liver = read.csv("NSTissueSpecific_Protein_Liver.csv")

fix.read.csv = function(x)
{
  names = x[,1]
  gee = x[,2:dim(x)[2]]
  rownames(gee) = names
  return(gee)
}

tes.brain = fix.read.csv(tes.brain)
tes.liver = fix.read.csv(tes.liver)
tens.brain = fix.read.csv(tens.brain)
tens.liver = fix.read.csv(tens.liver)

```


```{r, echo = FALSE}
library(GeneNet)

target_liver = cbind(tes.liver, tens.liver)

pacor.ssec.brain = c()

for (i in 1:174)
{
  test = data.frame(tes.brain[,i], target_liver)
  estimate = ggm.estimate.pcor(test, method = "static")
  edge = network.test.edges(estimate) # pvalue may be fdr... :P, but i guess it doesn't matter??
  
  # calculate ssec
  
  this = edge[edge$node1 == 1,]
  score = sum(-log(this$pval))/length(target_liver)
 
  pacor.ssec.brain = c(pacor.ssec.brain, score) 
}



```

```{r, echo = FALSE, eval = FALSE}

# ARCHIVE BAD STUFF

test = data.frame(tes.brain[,1], target_liver)
estimate = ggm.estimate.pcor(test, method = "static") #, lambda = 0) # lambda??
edge = network.test.edges(estimate)

n2kappa(30, p = 577)

pval = cor0.test(estimate, kappa = 29)

kappa2n(29, p = 2)


brain.liv = bicorAndPvalue(pacor.brain_data, pacor.brain_data, use = 'pairwise.complete.obs')

cor = cor2pcor(brain.liv$bicor)
cor2 = pcor.shrink(pacor.brain_data)

```
  